---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: technova-weather-app-pipeline 
  namespace: ${{ values.namespace }}
spec:
  pipelineRef:
    name: technova-weather-app
  params:
    - name: ARGOCD_SERVER
      value: ${{ values.argocdServer }}
    - name: ARGOCD_USERNAME
      value: ${{ values.argocdUsername }}
    - name: ARGOCD_PASSWORD
      value: ${{ values.argocdPassword }}
    - name: REPO_URL
      value: "https://github.com/${{ values.orgName }}/${{ values.repoName }}.git"
    - name: DEST_NAMESPACE
      value: ${{ values.namespace }}
    - name: DEST_SERVER
      value: "https://kubernetes.default.svc"
    - name: IMAGE_APP_PATH
      value: "deploy/k8s/image"
    - name: MAIN_APP_PATH
      value: "deploy/k8s/app"
  taskRunTemplate:
    serviceAccountName: pipeline
  workspaces:
    - name: output
      volumeClaimTemplate:
        metadata:
          name: git-clone-pvc
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
