---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{ values.repoName }}-api
  description: Weather REST API exposed by Spring Boot backend
  tags:
    - rest
    - openapi
    - weather
spec:
  type: openapi
  lifecycle: experimental
  owner: ${{ values.orgName }}
  definition:
    $text: https://springboot-route-${{ values.namespace }}.apps.cluster-${{ values.clusterid }}.dynamic.redhatworkshops.io/v3/api-docs
