---
apiVersion: backstage.io/v1alpha1
kind: ${{ values.entityKind }}
metadata:
  name: ${{ values.repoName }}
  annotations:
    github.com/project-slug: ${{ values.orgName }}/${{ values.repoName }}
  tags:
    - springboot
    - api
    - microservice
spec:
  type: ${{ values.applicationType }}
  lifecycle: ${{ values.lifecycle }}
